language:
  - elisp
compiler:
  - gcc
notifications:
  email:
    recipients:
      - ab.ioryz@gmail.com
    on_success: always
    on_failure: always
sudo: required
env:
  matrix:
install:
  - sudo apt-get -qq update
  - ln -s emacs-init ${HOME}/.emacs.d
  - cd ${HOME}/.emacs.d
  - ./git_pulls.sh
script:
  - emacs -nw
