language: emacs-lisp
notifications:
  email:
    recipients:
      - ab.ioryz@gmail.com
    on_success: always
    on_failure: always
sudo: required
env:
  matrix:
    - EMACS=emacs24
install:
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get install -y -qq emacs24 emacs24-el;
    fi
  - ln -s ${HOME}/build/iory/emacs-init ${HOME}/.emacs.d
  - cd ${HOME}/.emacs.d
  - ./git_pulls.sh
script:
  - emacs -nw
